### PR TITLE
solve the task

### PR DESCRIPTION
**Pull request by esidarapp**

### CODE REVIEW

**Comment by esidarapp** [comment]
I dont know what to do with this error :
StructureTest.init:27 You should not rename base core.basesyntax package and path to project and project name should not contain spaces or words in cyrillic
I didn`t rename anything

**Review by olekskov — CHANGES_REQUESTED** [review]
Test is failing with message
java.lang.AssertionError: Class Circle should have some parent class with common state for all figures - color

In general structure should be following:
You have abstract parent class figure that contains common field `color`.
It also implements 2 interfaces, one for area calculation behaviour, second for ability to be drawed

Regarding your question:
Please check that path to project doesn't contain any RU/UA symbols in naming.
e.g. C:\users\Євген\ideaProjects or anything similar

**Comment by esidarapp** [comment]
I created new pull request for this task.
https://github.com/mate-academy/jv-oop-advanced/pull/1453

**Review by okuzan — CHANGES_REQUESTED** [review]
Only changes to this PR will be tracked and reviewed from now on

**Pull request closed without merging**
